---
title: "Literature_Rev_2023"
author: "Ken Suzuki"
date: "2023-09-02"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE, echo = FALSE, message = FALSE}
library(readxl)
library(dplyr)
library(ggplot2)
library(knitr)
library(tidyverse)
library(gt)

# Read excel file
master_dat <- read_excel("~/Desktop/IRP/Literature_review_2023/raw_data/Dat_01.xlsx")
```


#### 1) Obtain mean score for each study
```{r, echo=FALSE} 
# Get Row Means and Column Means.
study_mean <- master_dat %>%
  slice(4:n()) %>%
  select(-c(1, 3))

# Replace "YES" with 1 and "NO" with 0 in columns Q01 to Q47
study_mean <- study_mean %>%
  mutate(across(Q01:Q47, ~ case_when(
    . == "Yes" ~ as.numeric(1),
    . == "No" ~ as.numeric(0),
    is.na(.) ~ NA_real_
  )))

study_mean <- study_mean %>% 
  mutate(across(starts_with("Q"), as.numeric))

# Calculate row means for columns Q01 to Q47, rounded to 3 decimal places
study_mean <- study_mean %>%
  rowwise() %>%
  mutate(Mean = round(mean(c_across(Q01:Q47), na.rm = TRUE), 3)) %>%
  ungroup()

# Create tables
study_table <- master_dat %>%
  left_join(study_mean, by = "ID") %>%
  select(ID, Study, Author, Mean) 

# Remove first three rows from study_table
study_table <- study_table %>%
  slice(4:n())

# Create gt table and change the font size
gt_table <- gt(study_table) %>%
  tab_options(
    table.font.size = px(13)  # Adjust the font size here
  )

# Display the gt table
gt_table

```

### 2) Obtain mean scores for each question
```{r, echo=FALSE}
# Calculate column means 
question_mean <- study_mean %>%
  select(-ID) %>%  # Remove ID column
  summarise(across(everything(), \(x) round(mean(x, na.rm = TRUE), 3)))

# Extract the third row and transpose it
question_table <- master_dat %>% 
  slice(3) %>%
  gather(key = "variable", value = "value", -ID) 

# Remove the first two rows and the first column from the transposed dataset
question_table <- question_table %>%
  slice(-(1:2)) %>%
  select(-ID)   

# Extract the first row and transpose it
V1 <- master_dat %>% 
  slice(1) %>%
  gather(key = "variable", value = "value", -ID) 

# Remove the first two rows and the first column from the transposed dataset
V1 <- V1 %>%
  slice(-(1:2)) %>%
  select(-ID)   

# Extract the first row and transpose it
V2 <- master_dat %>% 
  slice(2) %>%
  gather(key = "variable", value = "value", -ID) 

# Remove the first two rows and the first column from the transposed dataset
V2 <- V2 %>%
  slice(-(1:2)) %>%
  select(-ID)   

# Combine value columns of V1 and V2 into question_table
question_table <- question_table %>%
  left_join(V1, by = "variable") %>%
  left_join(V2, by = "variable")

# Transpose question_mean and convert it into a data frame suitable for joining
question_mean <- question_mean %>%
  gather(key = "variable", value = "Mean")

# Add question_mean values as the new variable "Mean"
question_table <- question_table %>%
  left_join(question_mean, by = "variable")

# Add question_mean values as the new variable "Mean"
question_mean <- question_mean %>%
  gather(key = "variable", value = "Mean") %>%
  mutate(Mean = round(Mean, 2))
  
# Rename variables
question_table <- question_table %>% 
  rename(ID = variable,
         Question = value.x,
         Section = value.y,
         Topic = value)

# Change the order of appearance
question_table <- question_table %>% 
  select(ID, Section, Topic, Question, Mean)

# Create gt table and change the font size
gt_question_table <- gt(question_table) %>%
  tab_options(
    table.font.size = px(13)  # Adjust the font size here
  )
gt_question_table
```

```{r, echo=FALSE}

# Compute the mean by section
section_table <- question_table %>%
  group_by(Section) %>%
  summarise(Mean = mean(Mean, na.rm = TRUE)) %>%
  mutate(Mean = round(Mean, 3))

# Compute the mean by Topic
topic_table <- question_table %>%
  group_by(Topic) %>%
  summarise(Mean = mean(Mean, na.rm = TRUE)) %>%
  mutate(Mean = round(Mean, 3))

# Create gt table and change the font size
gt_section_table <- gt(section_table) %>%
  tab_options(
    table.font.size = px(13)  # Adjust the font size here
  )
gt_section_table

# Create gt table and change the font size
gt_topic_table <- gt(topic_table) %>%
  tab_options(
    table.font.size = px(13)  # Adjust the font size here
  )
gt_topic_table
```